version: '3.8'

services:
    app:
        build: .
        volumes:
            -  .:/var/www/html:uid=1001,gid=1001
        networks:
            - laravel_network

    nginx:
        image: nginx:alpine
        ports:
            - "127.0.0.1:8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    blackfire:
        image: blackfire/blackfire:2
        environment:
            # Exposes BLACKFIRE_SERVER_* environment variables from the host:
            BLACKFIRE_SERVER_ID:
            BLACKFIRE_SERVER_TOKEN:

            # Exposes BLACKFIRE_CLIENT_* environment variables
            # allowing the client to communicate with Blackfire's API:
            BLACKFIRE_CLIENT_ID:
            BLACKFIRE_CLIENT_TOKEN:
        networks:
            - laravel_network

networks:
    laravel_network:
        name: laravel_network
