services:
  laravel_app:
    build: ./laravel
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - laravel_db
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.99"
          memory: 2GB

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - laravel_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.99"
          memory: 2GB

volumes:
  laravel_db_data:
